#!/bin/bash
FILE="${1}"
DOC="$(echo ${FILE%.*})"
THEME="$HOME/workspace/asciidoctor"
STYLE=basic

#asciidoc -a icons -b html5 --theme=${STYLE} "${DOC}.adoc"
#wkhtmltopdf -s Letter "${DOC}.html" "${DOC}.pdf"
#rm "${DOC}.html"
asciidoctor-pdf -a allow-uri-read -a pdf-themesdir=$THEME/themes -a pdf-theme=$STYLE -a pdf-fontsdir=$THEME/fonts -r asciidoctor-diagram "${DOC}.adoc"
rm -f "${DOC}.html"
