#!/bin/bash
FILE="${1}"
DOC="$(echo ${FILE%.*})"
THEME="$HOME/.asciidoc/themes/"
STYLE=artg

asciidoctor-pdf -r asciidoctor-diagram -a pdf-stylesdir=${THEME} -a pdf-style=${STYLE} -o "${DOC}.pdf" "${DOC}.adoc"
rm -f diag-*png
