#!/bin/bash
# updater
major=$(git ls-remote --tags https://github.com/asciidocfx/AsciidocFX/ | grep refs/tags/v | grep -v -e beta -e rc[123456789] -e RC[123456789] -e "\^{}" | awk '{print $2}' | sed "s/refs\/tags\///" | awk -F'.' '{print $1}' | sort | uniq)

minor=$(git ls-remote --tags https://github.com/asciidocfx/AsciidocFX/ | grep refs/tags/v | grep -v -e beta -e rc[123456789] -e RC[123456789] -e "\^{}" | grep $major | awk -F'.' '{print $2}' | sort -g | uniq | tail -1)

patch=$(git ls-remote --tags https://github.com/asciidocfx/AsciidocFX/ | grep refs/tags/v | grep -v -e beta -e rc[123456789] -e RC[123456789] -e "\^{}" | grep $major.$minor | awk -F'.' '{print $3}' | sort -g | uniq | tail -1)

vers=""

if [ "$patch" = "" ]; then
    vers=$major.$minor
else
    vers=$major.$minor.$patch
fi

IDIR=/usr/local/lib
BDIR=/usr/local/bin

echo "Installing $vers"

sudo rm -f /tmp/$vers.linux.tar.gz
wget -qc https://github.com/asciidocfx/AsciidocFX/releases/download/$vers/AsciidocFX_Linux.tar.gz -O /tmp/$vers.linux.tar.gz

sudo rm ${BDIR}/AsciidocFX
sudo rm -rf ${IDIR}/AsciidocFX/
sudo tar axf /tmp/${vers}.linux.tar.gz -C ${IDIR}
sudo find ${IDIR} -type d -exec chmod 777 "{}" \;
sudo ln -s ${IDIR}/AsciidocFX/AsciidocFX ${BDIR}/AsciidocFX

