#!/bin/bash
digger(){
    echo ${1} `dig +nocmd +noall +answer +ttlid @${2} a ${3}`
}
for ns in `grep nameserver /etc/resolv.conf | awk '{print $2}'`
do
    digger localhost $ns $1
done
digger ns1.arthomson.com 10.0.100.15 ${1}
digger ns2.arthomson.com 10.0.103.15 ${1}
digger ktk1.smartt.com 69.31.170.249 ${1}
digger ktk2.smartt.com 69.67.179.249 ${1}
digger ns1.smartt.com 69.31.170.53 ${1}
digger ns2.smartt.com 69.67.179.249 ${1}
digger ns1.name.com 162.88.61.47 ${1}
digger ns2.name.com 162.88.60.47 ${1}
digger ns3.name.com 162.88.61.49 ${1}
digger ns4.name.com 162.88.60.49 ${1}
digger ns1.digitalocean.com ns1.digitalocean.com ${1}
digger ns2.digitalocean.com ns2.digitalocean.com ${1}
digger ns3.digitalocean.com ns3.digitalocean.com ${1}
digger 222.222.opendns.com 208.67.222.222 ${1}
digger 220.220.opendns.com 208.67.220.220 ${1}
digger 222.220.opendns.com 208.67.222.220 ${1}
digger 220.222.opendns.com 208.67.220.222 ${1}
digger 8.8.8.8.google.com  8.8.8.8 ${1}
digger 8.8.4.4.google.com  8.8.4.4 ${1}
digger 9.9.9.9.quad9.ibm   9.9.9.9 ${1}
digger 1.1.1.1.cloudflare  1.1.1.1 ${1}
digger 1.0.0.1.cloudflare  1.0.0.1 ${1}

