#!/bin/bash

function removecontainers(){
    docker stop $(docker ps -aq)
    docker rm $(docker ps -aq)
}

armageddon(){
    #removecontainers
    docker network prune -f
    docker rmi -f $(docker images --filter dangling=true -qa)
    docker volume rm $(docker images --filter dangling=true -qa)
    #docker rmi -f $(docker images -qa)
}

armageddon
