#!/bin/bash
# go language updater
major=$( git ls-remote --tags https://github.com/golang/go | grep refs/tags/go | grep -v -e beta -e rc[123456789] | awk '{print $2}' | sed "s/refs\/tags\///" | awk -F'.' '{print $1}' | sort | uniq)

minor=$( git ls-remote --tags https://github.com/golang/go | grep refs/tags/go | grep -v -e beta -e rc[123456789] | awk '{print $2}' | sed "s/refs\/tags\///" | grep ^$major | awk -F'.' '{print $2}' | sort -g | uniq | tail -1)

patch=$( git ls-remote --tags https://github.com/golang/go | grep refs/tags/go | grep -v -e beta -e rc[123456789] | awk '{print $2}' | sed "s/refs\/tags\///" | grep ^$major.$minor | awk -F'.' '{print $3}' | sort -g | uniq | tail -1)

vers=""

if [ "$patch" = "" ]; then
    vers=$major.$minor
else
    vers=$major.$minor.$patch
fi

IDIR=/usr/local/lib
BDIR=/usr/local/bin

echo "Installing $vers"

sudo rm -f /tmp/$vers.linux-amd64.tar.gz
wget -qc https://dl.google.com/go/$vers.linux-amd64.tar.gz -O /tmp/$vers.linux-amd64.tar.gz

sudo ls ${IDIR}/go/bin | sudo xargs -I {} rm -f ${BDIR}/{}
sudo rm -rf ${IDIR}/go
sudo tar axf ${vers}.linux-amd64.tar.gz -C ${IDIR}
sudo ls ${IDIR}/go/bin | sudo xargs -I {} ln -sf ${IDIR}/go/bin/{} ${BDIR}/{}
sudo rm -f /tmp/$vers.linux-amd64.tar.gz

